<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jotttt
 * Date: Fri, 24 Jul 2015 09:45:01 +0000
 */

$conf['title'] = 'TTÜ_test_design';
$conf['template'] = 'writr';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
